@startuml deployment-diagram-option-1
'deployment diagram
caption Deployment Diagram: Level 2 view, option 1

skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}
skinparam artifact{
  BorderColor black
  BackgroundColor transparent
}
skinparam component{
  BorderColor black
  BackgroundColor transparent
}
skinparam actor{
  BorderColor black
  BackgroundColor transparent
}
skinparam database{
  BorderColor black
  BackgroundColor transparent
}

rectangle "EDDIE Framework" {
  node "Docker Runtime" <<Local Computing Infrastructure>> as local {    
    artifact "Permission\nFacade" <<Container>> as consentFacade
    component "Interoperable\nCommunication" as comm
    artifact "Admin\nConsole" <<Container>> as adminConsole
    artifact "Streaming\nInfrastructure" <<Container>> as broker
    database "\tDatabase\t\n" <<Container>> as database
  }
}
  consentFacade -right- comm
  adminConsole -left- comm
  comm -down- broker
  comm -down- database
  adminConsole -down- database 
  
@enduml