@startmindmap crosscutting-concepts
'mindpam diagram
caption Mindmap: Crosscutting concepts

<style>
mindmapDiagram {
  node {
    BackgroundColor transparemt
    HorizontalAlignment center
  }
}
</style>

* Crosscutting\nConcepts

-- Domain\nModels
---_ CIM
---_ SAREF
-- Architectural\nPatterns
---_ Request/\nResponse
---_ Publish/\nSubscribe
-- Development\nProcess
---_ Test Driven\nDevelopment
---_ CI/CD

++ User\nExperience
+++_ Websites
+++_ Smartphone\nApps
++ Security
+++_ HTTPS
+++_ SASL/SSL
++ Operation
+++_ Availability
+++_ Scalability
+++_ Persistence
++ Under the\nHood
+++_ Error Handling
+++_ Logging
+++_ Multithreading
+++_ Persistence 


@endmindmap