@startuml get-historical-data-france
'sequence diagram
caption Sequence Diagram: The consumer gives consent to an eligible party for access to historical data.

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber

!pragma teoz true

actor "Consumer" as user
participant "EP\nWebsite" as website

box "EDDIE Framework" #transparent
  participant "Consent\nFacade" as facade
  participant "Interoperable\nCommunication" as comm
  participant "Consent\nFacade" as facade
 end box


box "ENEDIS" #transparent
  box "Website" #transparent
    participant "Consent\n Admin Portal" as adminPortal
  end box

  box "API" #transparent
    participant "Meter Data\nPortal" as ENEDIS_API
  end box 
end box

user -> website: login()
user -> website: connectMyData()
activate website
  website -> facade : getConsentPortals()
    activate facade
    facade -->> website : countries,\nadminPortals
  deactivate facade
  website -->> user : show(countries,\nadminPortals)
deactivate website

user -> website : select(admin\nPortal)
activate website
  website -> facade : forward(adminPortal)
  activate facade
    facade -->> comm : get\nConsent(\nconsumer)
  deactivate facade
    comm -> website : return(ConsentButton) 
    'explain button in text
  website -->> user : show(ConsentButton)
deactivate website

user -> adminPortal: click(ConsentButtonAndRedirect)
user ->adminPortal: login()
user -> adminPortal: accept()
'mention forwarded SM_ID

adminPortal -> adminPortal: forward(information)
comm -> adminPortal: get(ClientID,ClientSecret)
activate adminPortal
  adminPortal-->> comm : ClientID,ClientSecret
deactivate adminPortal

comm -> ENEDIS_API: getToken(ClientID,ClientSecret)
activate ENEDIS_API
    ENEDIS_API-->> comm: Token
deactivate ENEDIS_API

comm -> ENEDIS_API: requestData(Token)
activate ENEDIS_API
  ENEDIS_API -->> comm: Data
deactivate ENEDIS_API




@enduml