@startmindmap crosscutting-concepts
'mindpam diagram
caption Mindmap: Crosscutting concepts

<style>
mindmapDiagram {
  node {
    BackgroundColor transparemt
    HorizontalAlignment center
  }
}
</style>

* Crosscutting\nConcepts

-- Architectural\nPatterns
---_ Microfrontends
---_ Adapter
---_ Publish/subscribe
-- Development\nProcess
---_ Test-driven
---_ CI/CD
-- Domain\nModels
---_ CIM
---_ SAREF
---_ SGAM

++ Security
+++_ HTTPS
+++_ SASL-TLS
++ User\nExperience
+++_ GUIs
+++_ Containers
++ Other\nConcepts
+++_ Dataspaces

@endmindmap