@startuml

actor FinalCustomer

frame EPWebsite {

node onboarding_process [
    EP Client Onboarding Process
    ----
    with button <i>connect my data</i>
]

component EDDIEFrameworkPopup [
    EDDIE Framework Popup GUI
    ----
    takes serviceId
]

node data_based_app [
    EP data based app
    ----
    just consumes data
]

onboarding_process -right- data_based_app

}

frame EDDIEFramework {

component EDDIEConsentFacade [
    EDDIE Consent Facade
]

component EDDIEICL [
    EDDIE Interoperable Communication Layer
]

component PAConnectorEDA [
    PA Connector EDA (AT)
    ....
    uses EDA onboarding details for service
]

component PAConnectorEnedis [
    PA Connector Enedis
    ....
    uses Enedis onboarding details for service
]

database EDDIEDatabase [
    PAOnboardingDetails
    Generic process state information (MetaData)
    PA process state information
    Audit information
]


queue topic_paconn_eda [
    topic paconn_eda
    both directions
]

queue topic_paconn_enedis [
    topic paconn_enedis
    both directions
]

queue topic_dbapp [
    topic db_app_per_serviceid
    both directions (back for termination)
]

queue topic_cf_icl [
    topic consentfacade_icl
    both directions (back for immediate status updates)
]

EDDIEICL -up- topic_dbapp
topic_dbapp -up-data_based_app

EDDIEICL -- topic_paconn_eda
topic_paconn_eda -- PAConnectorEDA

PAConnectorEDA -- EDDIEDatabase : uses
PAConnectorEnedis -- EDDIEDatabase : uses

EDDIEICL -- topic_paconn_enedis
topic_paconn_enedis -- PAConnectorEnedis

EDDIEICL -right- EDDIEDatabase : uses

EDDIEConsentFacade -right- topic_cf_icl : CIMConsentRequest / back process state
topic_cf_icl -right- EDDIEICL

EDDIEConsentFacade -- EDDIEDatabase : uses

onboarding_process -- EDDIEFrameworkPopup : shows after click on button

}

EPWebsite -- EDDIEFramework : communicates with

EDDIEFrameworkPopup .down. EDDIEConsentFacade : < gets masterdata and gui for PA from
EDDIEFrameworkPopup -down- EDDIEConsentFacade : > filled standardised CIMConsentRequest

FinalCustomer -- EPWebsite : uses

@enduml