@startuml marketplace-check-aiida

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Eligible Party" as ep
box "Marketplace System" #transparent
  participant "EP Web App" as app
  participant "Marketplace \nApplication" as marketplace
end box

box "AIIDA System" #transparent
  participant "AIIDA \nEmbedded App" as aiida
end box

ep -> app : Search for \nAIIDA instances
app -> marketplace : Run data request
activate marketplace
marketplace -> aiida : Send query
activate aiida
aiida -> aiida : Run Query
aiida -->> marketplace : Results
deactivate aiida
marketplace -->> app : Matching \nAIIDA instances
deactivate marketplace






@enduml