@startuml marketplace-authenticate-user

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Customer" as customer
box "Marketplace System" #transparent
participant "Customer \nMobile App" as app
participant "Marketplace \nApplication" as marketplace
participant "IAM" as iam
participant "Database" as database
end box

' get authorization code
customer -> app : Login
app -> iam : Authenticate user
activate iam
iam -> database : Validate user
activate database
database -->> iam : OK
deactivate database
iam -->> app : Authorization code
deactivate iam

' get access tokens:
' - Access Token (JWT): Used to access backend resources.
' - ID Token (JWT): Contains user profile information.
' - Refresh Token (optional): Used to obtain new access tokens when they expire.
app -> iam : Get tokens
activate iam
iam -->> app : Tokens
deactivate iam
app -> customer : OK

' marketplace validates tokens
customer -> app : Any action
app -> marketplace : Request with\n access token
activate marketplace

' The marketplace has a public key from IAM (acquired occasionally) that is used to validate tokens.

marketplace -> marketplace : Validate\ntoken
marketplace -> marketplace : Process\nrequest
marketplace -->> app : Response
deactivate marketplace

@enduml
