@startuml marketplace-browse-requests

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Customer" as customer
box "Data Services Marketplace System" #transparent
  participant "Marketplace \nPWA" as app
  participant "Marketplace \nBackend" as marketplace
  participant "Database" as database
end box

customer -> app : Discover data services
app -> marketplace : Get data services
activate marketplace
marketplace -> database : Get data services
activate database
database -->> marketplace : Data Services
deactivate database
marketplace -->> app : Data Services
deactivate marketplace

@enduml