@startuml marketplace-submit-feedback

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Customer" as customer
box "Marketplace System" #transparent
  participant "Marketplace \nFrontend" as app
  participant "Marketplace \nBackend" as marketplace
  participant "Database" as database
end box

customer -> app : Fill out form
app -> marketplace : Submit form
activate marketplace
marketplace -> database : Store feedback
activate database
database -->> marketplace : OK
deactivate database
marketplace -->> app : OK
deactivate marketplace

@enduml