@startuml marketplace-register-aiida

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Customer" as customer
box "Marketplace System" #transparent
  participant "Customer \nMobile App" as app
  participant "Marketplace \nApplication" as marketplace
  participant "IAM" as iam
  participant "Database" as database
end box

box "AIIDA System" #transparent
  participant "AIIDA \nEmbedded App" as aiida
end box

customer -> app : Register AIIDA
app -> aiida : Request AIIDA information
aiida -> app : Provide AIIDA information
app -> marketplace : Register AIIDA
activate marketplace
marketplace -> database : Store AIIDA \ninformation
activate database
database -->> marketplace : OK
deactivate database
marketplace -->> app : OK
deactivate marketplace





@enduml