@startuml marketplace-access-service

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Customer/EP" as customer
box "Data Services Marketplace System" #transparent
  participant "Marketplace \nFrontend" as app
  participant "Marketplace \nBackend" as marketplace
end box

box "EP System" #transparent
  participant "EP Service" as ep
end box

customer -> app : Select data service
activate app
app -> marketplace : Load data service
activate marketplace
marketplace --> app : Provide data
deactivate marketplace
app -> customer : Show data service information
customer -> app : Click on redirect button
app -> ep : Redirect to EP system
deactivate app
activate ep
ep -->> customer : Show data service
deactivate ep

@enduml