@startuml marketplace-check-aiida

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Eligible Party" as ep
box "Marketplace System" #transparent
  participant "EP Web App" as app
  participant "Marketplace" as marketplace
  participant "IAM" as iam
  participant "Database" as database
end box

box "AIIDA System" #transparent
  participant "AIIDA \nEmbedded App" as aiida
end box

ep -> app : Search AIIDA
app -> marketplace : Send query
activate marketplace
marketplace -> database : Get all AIIDA IPs
activate database
database --> marketplace : AIIDA IPs
deactivate database
marketplace -> aiida : Send query
activate aiida
aiida -> aiida : Run Query
aiida --> marketplace : Results
deactivate aiida
marketplace -> app : AIIDA IDs
deactivate marketplace






@enduml