@startuml marketplace-create-account

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "User" as user
box "Data Services Marketplace System" #transparent
  participant "Marketplace \nPWA" as app
  participant "IAM" as iam
  participant "Database" as database
end box

user -> app : Request to create new Account
activate app
app -> iam : Redirect user to IAM
activate iam
deactivate app
iam -> user: Show registration form
user -> iam : Fill out registration form / provide credentials
iam -> database : Store account
activate database
database -->> iam : OK
deactivate database
iam -> app : Redirect with Authorization Code
deactivate iam

@enduml
