@startuml marketplace-create-account

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "User" as user
box "Marketplace System" #transparent
  participant "Marketplace \nFrontend" as app
  participant "IAM" as iam
  participant "Database" as database
end box

user -> app : Register/login
app -->> app : IAM redirection
app -> iam : Create account
activate iam
iam -> database : Store account
activate database
database -->> iam : OK
deactivate database
iam -->> app : OK
deactivate iam

@enduml