@startuml marketplace-browse-requests

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Customer" as customer
box "Marketplace System" #transparent
  participant "Customer \nMobile App" as app
  participant "Marketplace" as marketplace
  participant "Database" as database
end box

customer -> app : Get data \nrequests/services
app -> marketplace : Get data \nrequests/services
activate marketplace
marketplace -> database : Get data \nrequests/services
activate database
database --> marketplace : Requests/services
deactivate database
marketplace --> app : Requests/services
deactivate marketplace

@enduml