@startuml consent-revocation-meter-data-admin
'sequence diagram
caption Sequence Diagram: The MDA revokes the consent.

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber

participant "Meter Data\nAdministrator" as user
box "EDDIE Framework" #transparent
  participant "Interoperable\nCommunication" as comm
end box
participant "Service\n" as service

user -> comm : revokeConsent(\nconsumer,\neligibleParty)
comm -> service : forward(\nRevocation)
service -> service : terminate()

@enduml