@startuml reg-connector-sends-data
'sequence diagram
caption Sequence Diagram: The Regional/AIIDA Connector sends the data to a Service

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

box "EDDIE Framework" #transparent
  box "Interoperable Communication" #transparent
    participant "Regional/AIIDA\nConnector" as regionalConnector
    participant "Message\nProducer" as messageProducer
  end box
  participant "Streaming\nInfr." as streamingInfrastructure
end box

participant "Service\n" as service

service -> streamingInfrastructure : createTopic(\ntopicName)
service -> streamingInfrastructure : subscribe(\ntopicName)


regionalConnector -> messageProducer : send(data)
messageProducer -> streamingInfrastructure : publish(\ndata, topicName)

streamingInfrastructure -> service  : data

@enduml