@startuml aiida_deployment_view
' component diagram

' skinparam linetype ortho

skinparam artifact{
  BorderColor black
  BackgroundColor transparent
}
skinparam node{
  BorderColor black
  BackgroundColor white
}
skinparam rectangle{
  ' BorderColor transparent
  BackgroundColor transparent
  FontColor black
}

rectangle "AIIDA System" {
  node "In-house Device" as aiida {
    artifact "AIIDA Application" as aiidaapp
    artifact "EMQX \nMQTT Broker" as emqx
    artifact "TimescaleDB" as db
    artifact "Keycloak" as kc

    aiidaapp -down- emqx : MQTT
    aiidaapp -down- db : SQL
    aiidaapp -down- kc : OIDC
    db -[hidden]right- emqx
    kc -[hidden]right- emqx
  }

  node "Eligible Party Infrastructure"  as epInfra{
    artifact "AIIDA Region\nConnector" as regcon
    artifact "EMQX \nMQTT Broker" as broker
    artifact "EMQX \nIAM DB" as emqxiam

    broker -left- emqxiam : SQL
    regcon -down- broker : MQTT
    regcon -down- emqxiam : SQL

  }

  aiidaapp -left- broker : MQTT
  aiidaapp -up- REST : HTTP
  aiidaapp -up- UI : HTTP

  ' frame "Device Austria" as device2
  ' frame "Device France" as device3
node "Data Source" as adapterDevice
}
node "Measuring Device" as measuringdevice

adapterDevice -left- aiidaapp : Modbus
adapterDevice -left- emqx : MQTT

measuringdevice -up- adapterDevice : DSMR, Modbus, M-Bus, etc.

}

@enduml