@startuml aiida_deployment_view
'component diagram

' skinparam linetype ortho

skinparam artifact{
  BorderColor black
  BackgroundColor transparent
}
skinparam node{
  BorderColor black
  BackgroundColor white
}
skinparam rectangle{
  ' BorderColor transparent
  BackgroundColor transparent
  FontColor black
}

rectangle "AIIDA System" {
  node "Eligible Party Infrastructure"  as epInfra{
      artifact "AIIDA Region\nConnector" as regcon
    artifact "EMQX \nMQTT Broker" as broker
    artifact "EMQX \nIAM DB" as emqxiam

    broker -right- emqxiam : SQL
    regcon -down- broker : MQTT
    regcon -down- emqxiam : SQL

  }

  node "Smartphone" as smartphone{
    artifact "AIIDA Smartphone App" as app

  }
  node "In-house Device" as aiida {
    artifact "AIIDA Embedded App" as embapp
    artifact "NanoMQ \nMQTT Broker" as nano
    artifact "TimescaleDB" as db

    embapp -down- nano : MQTT
    embapp -down- db : SQL
    db -[hidden]right- nano
  }

  embapp -up- app : HTTP
  embapp -right- broker : MQTT

  ' frame "Device Austria" as device2
  ' frame "Device France" as device3
node "Data Source" as adapterDevice
}
node "Metering Device" as smartmeter

adapterDevice -left- embapp : HTTP
adapterDevice -left- nano : MQTT

smartmeter -up- adapterDevice : DSMR

@enduml