@startuml aiida_deployment_view
'component diagram
caption Component Diagram: Level 2 view

skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}
skinparam component{
  BorderColor black
  BackgroundColor transparent
}
skinparam actor{
  BorderColor black
  BackgroundColor transparent
}
skinparam database{
  BorderColor black
  BackgroundColor transparent
}
skinparam collections{
  BorderColor black
  BackgroundColor white
}
skinparam rectangle{
  ' BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}


node "Eligible Party Infrastructure"  as epInfra{
  component "EDDIE Framework" {

    component "EDDIE \nCore" as eddie
    component "AIIDA Regional\nConnector" as regcon
  }
  component "EMQX IAM DB" as emqxiam
  component "EMQX MQTT Broker" as broker

  eddie -[hidden]down- emqxiam
  eddie -[hidden]down- broker
}
node "Local Network" {
  component "Smartphone" as smartphone{
    component "Smartphone App" as app

  }
  node "AIIDA Device" as aiida {
    component "Embedded App\n AIIDA Firmware" as embapp
    component "NanoMQ MQTT Broker" as nano
    component "TimescaleDB" as db
  }
  embapp -[hidden]down- nano
  nano -[hidden]down- db
  aiida -[hidden]up- smartphone
  embapp -up- app:DNS
 
}

node "Device Italy" as device1
node "Device Austria" as device2
node "Device France" as device3

node "Smart Meter" as smartmeter1
node "Enedis" as enedis
node "Smart Meter" as smartmeter2

device1 -left- smartmeter1:\n\nPhysical\ninterfaces
device2 -left- smartmeter2:\n\nPhysical\ninterfaces
device3 -left- enedis:\nTIC\n(2-wire)

regcon -left- embapp:HTTP/MQTT
embapp -[hidden]right- device2
embapp -right- device1:USB
embapp -right- device3:Modbus TCP
nano -right- device2:MQTT
nano -up-embapp
device1 -[hidden]down- device2
device2 -[hidden]down- device3
epInfra -[hidden]right- aiida



 

@enduml