@startuml eligible-party-terminates-service
'sequence diagram
caption Sequence Diagram: The eligible party terminates a Service

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Eligible\nParty" as user
box "Eligible Party Infrastructure" #transparent
  box "EDDIE Framework\n" #transparent
    participant "Admin\nConsole" as adminConsole
    box "Interoperable\nCommunication" #transparent
      participant "Regional\nConnectors" as regionalConnector
    end box
  end box
  participant "Service" as service
end box
box "Regional Data-sharing\nInfrastructure" #transparent
  participant "Consent\nAdmin Portal" as adminPortal
end box

user -> adminConsole : login(credentials)
user -> adminConsole : terminate(service)
activate adminConsole
  adminConsole -> adminConsole : terminate(service)
  adminConsole -> regionalConnector : revokeConsent(\ncustomers, service)
    activate regionalConnector
      regionalConnector -> adminPortal : revokeConsent(customers)
      activate adminPortal
        adminPortal -->> regionalConnector : consentStatus
      deactivate adminPortal
      regionalConnector -->> adminConsole : consentStatus
    deactivate regionalConnector
  adminConsole -->> user : consentStatus
deactivate adminConsole

@enduml