@startuml service-termination
'sequence diagram
caption Sequence Diagram: The eligible party terminates a running service.

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber

actor "Eligible\nParty" as user
box "EDDIE Framework" #transparent
  participant "Admin\nConsole" as adminConsole
  participant "Interoperable\nCommunication" as comm
end box
participant "Consent\nAdmin Portal" as adminPortal
participant "Meter Data\n Portal" as meterPortal

user -> adminConsole : terminate(\nservice)
activate adminConsole
  adminConsole -> comm : terminate(\nservice)
    activate comm
      comm -> adminPortal : terminate(\nservice)
      activate adminPortal
        adminPortal -> meterPortal : terminate(\ndataSharing)
        adminPortal -->> comm : consentStatus
      deactivate adminPortal
      comm -->> adminConsole : consentStatus
    deactivate comm
  adminConsole -->> user : consentStatus
deactivate adminConsole

@enduml