@startuml collect-consent-historical-data
'sequence diagram
caption Sequence Diagram: The customer fills out the consent form

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Customer" as user
box "EDDIE Framework" #transparent
  participant "Permission\nFacade" as website
  box "Interoperable Communication\n"  #transparent
    box "\t\tRegional Connector\t\t"  #transparent
      participant "Microfrontend" as microfrontend
    end box
  end box
end box

user -> website : connect(\nhistoricalData)
activate website
  website -->> user : show(popUp)
deactivate website

user -> website : select(country)
activate website
  website -> microfrontend : getMicrofrontend()
  activate microfrontend
    microfrontend -->> website : microfrontend
  deactivate microfrontend
  website -->> user : showForm(\nmicrofrontned)
deactivate website

user -> microfrontend : fillOutForm(requiredData)
activate microfrontend
  microfrontend -> microfrontend : requestConsent(\nrequiredData)
  microfrontend -->> user : show(redirection)
deactivate microfrontend


@enduml