@startuml deployment-diagram-marketplace

' skinparam linetype ortho
skinparam artifact{
  BorderColor black
  BackgroundColor transparent
}
skinparam rectangle{
  BorderColor black
  BackgroundColor transparent
}
skinparam node{
  BorderColor black
  BackgroundColor transparent
}

rectangle "Data Services Marketplace System" {
  node "Operator Infrastructure" as local {    
    artifact "Marketplace\nBackend" as marketplace
    artifact "Database" as database
    artifact "IAM" as iam

    marketplace -right- database : SQL
    iam -down- marketplace : HTTP
  }
node "User Device" as user {
  artifact "Marketplace Progressive Web App" as app
}
}

app -right- iam : HTTP
app -right- marketplace : HTTP
  
@enduml