@startuml deployment-diagram-marketplace

' skinparam linetype ortho
skinparam artifact{
  BorderColor black
  BackgroundColor transparent
}
skinparam rectangle{
  BorderColor black
  BackgroundColor transparent
}
skinparam node{
  BorderColor black
  BackgroundColor transparent
}

rectangle "Marketplace System" {
  node "Computing Infrastructure" as local {    
    artifact "Marketplace\nApplication" as marketplace
    artifact "Database" as database
    artifact "IAM" as iam

    database -down- marketplace : SQL
    database -right- iam : SQL
  }
node "User Device" as cust {
    artifact "Customer Mobile App" as customer
}
node "User Device" as elpa {
    artifact "EP Web App" as ep
}
ep -down[hidden]- customer
}

rectangle "AIIDA System" {
  artifact "AIIDA Embedded App" as aiida
}


ep -right- marketplace : HTTP
customer -right- marketplace : "HTTP  "

marketplace -down- aiida : HTTP


  
@enduml