@startuml aiida-frontend
'component diagram
caption Component Diagram: The AIIDA Frontend/App

skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}
skinparam component{
  BorderColor black
  BackgroundColor transparent
}
skinparam actor{
  BorderColor black
  BackgroundColor transparent
}
skinparam database{
  BorderColor black
  BackgroundColor transparent
}
skinparam rectangle{
  BorderColor black
  BackgroundColor transparent
}


node "In-house\nInfrastructure" {
  component "\tAIIDA" as aiida {
    component "AIIDA\nFrontend" as frontend
    component "  AIIDA\n  Backend" as backend
    interface " " as aiidaAPI

    frontend -right-( aiidaAPI
    aiidaAPI -right- backend
  }

}
actor "customer" as customer
component "AIIDA\nApp" as app

customer -down- frontend

customer -right- app
app -down-( aiidaAPI

@enduml