@startuml context-diagram
'context diagram
caption Context Diagram: Interactions between the EDDIE Framework and its environment

' skinparam linetype ortho
skinparam usecase {
  BorderColor black
  BackgroundColor transparent
}
skinparam rectangle {
  BorderColor black
  BackgroundColor transparent
}

rectangle "Poject Scope" #line:Gray;line.dashed {

  usecase "\n\nEDDIE\nFramework\n\n" as eddie
  ' #52cbff
  rectangle "AIIDA\n" as aiida
  ' #ffbd38
}
rectangle "Regional Data-sharing\n\tInfrastructure" as energy
' #7aff83
rectangle "Services\n" as services
' #ff52ab

aiida -right-> eddie :Real-time data
energy -up-> eddie :Historical data
eddie -right-> services :Real-time and historical data

@enduml