@startuml context-diagram
'context diagram
caption Context Diagram: Interactions between the EDDIE Framework and its environment

' skinparam linetype ortho
skinparam usecase {
  BorderColor black
  BackgroundColor transparent
}
skinparam rectangle {
  BorderColor black
  BackgroundColor transparent
}
skinparam collections {
  BorderColor black
  BackgroundColor white
}

rectangle "Project EDDIE Scope" #line:Gray;line.dashed {

  usecase "\n\nEDDIE\nFramework\n\n" as eddie
  ' #52cbff
  collections "AIIDA\n" as aiida
  ' #ffbd38
}
collections "Regional Data-sharing\n\tInfrastructure" as energy
' #7aff83
rectangle "Eligible\nParty" as services
' #ff52ab

aiida -right-> eddie : Send real-time data
energy -up-> eddie : Send historical data
eddie -right-> services : Send real-time and historical data

@enduml