@startuml deployment-diagram
'deployment diagram
caption Deployment Diagram: High-level view of the system

skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}
skinparam component{
  BorderColor black
  BackgroundColor transparent
}
skinparam artifact{
  BorderColor black
  BackgroundColor transparent
}
skinparam artifact{
  BorderColor black
  BackgroundColor transparent
}
skinparam node{
  BorderColor black
  BackgroundColor transparent
}
skinparam rectangle {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}

node "\t\tDocker Runtime\t\t" <<Eligible Party Infrastructure>> as epInfra{
  component "EDDIE Framework" as eddie
  artifact "Service" <<Container>> as service
  interface "\t\tKafka" as eddie1
  interface "\t\tKafka" as eddie2

  eddie -up- eddie1
  service -down-( eddie1 :Pull historical and\nreal-time data
  eddie -right- eddie2
}
node "In-house Infrastructure"  {
node "Docker Runtime" <<In-house Device>> as house{
  component "\tAIIDA\t" as aiida
}
node " " <<Smart Meter>> as meter{
  interface "P1" as p1
}
}

node "Regional Data-sharing\nInfrastructure"  as energyProvider {
  interface "HTTP" as energy1
}

' actor "Consumer" as consumer
' actor "Eligible\nParty" as ep

aiida --( p1 :Pull real-time data\n

eddie -down--( energy1 :Pull historical data
aiida -up--( eddie2 :Push real-time data\n\n

' consumer -down- aiida
' ep -down- eddie

@enduml