@startuml component-diagram-ep-website
'component diagram
caption Component Diagram: EP Website and Services
skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}
skinparam component{
  BorderColor black
  BackgroundColor transparent
}
skinparam actor{
  BorderColor black
  BackgroundColor transparent
}

skinparam rectangle{
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}
skinparam collections{
  BorderColor black
  BackgroundColor white
}



node "Eligible Party Infrastructure"  as epInfra{
  component "EDDIE Framework" as eddie
  component "EP Website" as ui
  collections "Service" as service

  ui -down-> eddie : consent
  service -right-> ui : result
  eddie -up-> service : data 
}

actor "Customer" as consumer

consumer -right- ui




@enduml