@startuml component-diagram-level-4-reg-con-AT
'component diagram
caption Component Diagram: Level 4 view with focus on the Regional Connector - Austria

skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}
skinparam component{
  BorderColor black
  BackgroundColor transparent
}
skinparam collections{
  BorderColor black
  BackgroundColor white
}
skinparam database{
  BorderColor black
  BackgroundColor transparent
}
skinparam rectangle{
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}

node "Eligible Party Infrastructure"  as epInfra{
  component "EDDIE Framework" as eddie {
    component "Consent Facade" as consentFacade
    component "Streaming\nInfrastructure" as database
    component "Interoperable Communication" as comm {
      component "Regional Connector - Austria" as regConAu {
        component "Ponton\nAdapter" as pontonAdapter
        component "Ponton XP\nMessanger" as pontonXP
        component "Translation\nService" as translationService
        rectangle " " as rec
        rec -[hidden]up- pontonAdapter
      }
      component "Message\nProducer" as messageProducer
    }

    consentFacade -down- translationService
    translationService -right-> pontonAdapter
    pontonAdapter -down-> messageProducer
    messageProducer -right-> database
  
    ' translationService -down- pontonXP
    pontonXP -right- pontonAdapter
  }
  node "Regional Data-sharing\nInfrastructure" as energyProvider {
    interface "Meter Data Portal" as dataPortal
    interface "Consent Admin Portal" as adminPortal
  
    adminPortal -[hidden]down- dataPortal
  }

  ' eddie -down- energyProvider
   pontonXP --down-( adminPortal
   pontonXP -down-( dataPortal






}





@enduml