@startuml eddie-framework-permission-request

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Customer" as customer
actor "Eligible Party" as ep

box "EP Infrastructure" #transparent
  participant "EP Website" as epApp
end box

box "EDDIE Framework" #transparent
  participant "EDDIE \nPopup" as popup
  participant "EDDIE \nCore" as core
  participant "Region \nConnector" as rc
end box

== Setup ==
ep -> core : Create \nData \nNeed
ep -> epApp : Embed \nEDDIE \nPopup

== Permission \nRequest ==
customer -> epApp : Click \nEDDIE \nPopup
epApp -> popup : Open \nPermission \nDialog
activate popup

' --- Detailed permission interaction ---
popup -> core : Fetch \nData Need
popup -> core : Fetch \nPermission \nAdministrators
popup -> core : Fetch \nRC Metadata
customer -> popup : Confirm \nData Need
customer -> popup : Select \nCountry \nand PA
popup -> rc : Fetch \nRC Element
customer -> popup : Interact \nwith \nRC Element
note over customer, rc
  Interaction varies by RC element
  (e.g., metering point, access token)
end note
popup -> rc : Send \nPermission Request\nbased \non user \ninteraction
popup -> core : Subscribe to \nPermission Status
' --- End detailed interaction ---

core -> rc : Forward \nPermission \nRequest
rc -> customer : Show \nConsent \nPortal
customer -> rc : Accept \nRequest
rc -->> core : Consent \nAccepted
core -->> popup : Show \nconfirmation
popup -->> customer : Confirmation \n/Success page
deactivate popup

== Data Access ==
ep -> core : Retrieve Data
core -> rc : Request \nValidated \nData
rc -->> ep : Provide Data

@enduml
