@startuml eddie-framework-retransmit-data

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Eligible Party" as ep

box "EP Infrastructure" #transparent
  participant "EP Website" as epInterface
end box

box "EDDIE Framework" #transparent
  participant "EDDIE Core" as eddie
  participant "Region \nConnector" as rc
  participant "Metered \nData \nAdministrator" as mda
  participant "Outbound \nConnectors" as oc
end box

== Retransmission Request ==
ep -> epInterface : Initiate retransmission\n(via API or Admin Console)
epInterface -> eddie : Send retransmission request
activate eddie

== Route to Region Connector ==
eddie -> rc : Route retransmission request
activate rc
rc -> mda : Retrieve re-requested historical data
mda -->> rc : Return historical data

par Parallel Acknowledgment & Data Transmission
    rc -> eddie : Acknowledge retransmission\n(success or failure)
    rc -> eddie : Send historical data
    eddie -> oc : Send data through all enabled outbound connectors
end

deactivate rc
deactivate eddie

@enduml
