@startuml context-diagram-dataspace
'context diagram

skinparam usecase {
  BorderColor black
  BackgroundColor transparent
}
skinparam rectangle {
  BorderColor black
  BackgroundColor transparent
}
skinparam collections {
  BorderColor black
  BackgroundColor white
}
skinparam actorStyle awesome
skinparam actor {
  BorderColor black
  BackgroundColor white
}

rectangle "Gaia-X" as gaiaX
collections "External Energy Data Space\n(e.g. OneNet, Omega-X)" as dataSpaces
usecase "\n\nEDDIE\nSystem\n\n" as eddie
collections "Metering\nDevice" as smartMeter
collections "Regional Data-sharing\nInfrastructures" as regionalData
rectangle "EP Website" as website
collections "Services" as service

actor "Eligible\nParty" as ep
actor "Customers" as customer

gaiaX -down-> eddie : Offers\ncompliance\nservices
gaiaX -down-> dataSpaces : Offers\ncompliance\nservices

eddie <-right-> dataSpaces : Data exchange\nbased on IDSA

service -right-> eddie : Access\ncustomer data
eddie -down-> regionalData : Accesses\ncustomer\nhistorical data
eddie -down-> smartMeter : Accesses\ncustomer\nreal-time data
eddie -left-> website : Provides \nEDDIE\nPopup
smartMeter -[hidden] regionalData : \t\t\t


ep -right-> service : Provides
ep -up-> website : Provides

website -right-> customer : Presents \nEDDIE\nPopup
customer -down-> eddie : Fills out\nEDDIE\nPopup
customer -[hidden]right- gaiaX : \t\t\t

@enduml
