@startwbs quality-tree
'work breakdown structure
caption Quality Tree: Overview of the quality requirements

<style>
wbsdiagram {
  node {
    BackgroundColor transparemt
    HorizontalAlignment center
    fontsize 14
  }
'   :depth(3) {
'     Linecolor white
'   }
}
</style>

* Quality

++ Performance
+++ Data Loss
++++_ No data\nshall be\n lost
+++ Latency of\n real-time\ndata
++++_ <1min

++ Availability
+++ Boot Time
++++_ <1min
' +++ Down Time
' ++++_ <60min/day

++ Compilance
+++ Implementation\nAct
++++_  Smart Grids\nTask Force
+++ Regional\nCoverage
++++_ >3 EU\ncountries

++ Security
+++ Unauthorized\nAccess
++++_ No access\n without\ncustomer\nconsent


@endwbs