@startwbs quality-tree
'work breakdown structure
caption Quality Tree: Overview of the quality requirements

<style>
wbsdiagram {
  node {
    BackgroundColor transparemt
    HorizontalAlignment center
    fontsize 14
  }
'   :depth(3) {
'     Linecolor white
'   }
}
</style>

* Quality Requirements

++ Deployment
+++_ Decentralized
+++ Configurations
++++_ Single-\ncommand\ndeployment
++++_ Deployment\noptions
+++ External\nComponent\nsupport
++++_ Databases
++++_ Streaming\ninfrastructures

++ Compliance
+++_ Implementing\nAct (SGTF)
+++ Regional\ncoverage
++++_ Access historical\n and real-time data
++++_ Identify technical\nregional hurdles

++ Security
+++ Authorization
++++_ Data access\nonly for\nauthorized\n Services
++++_ Consent\nrevocation



@endwbs