@startuml deployment-diagram
'deployment diagram

' skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}
skinparam component{
  BorderColor black
  BackgroundColor transparent
}
skinparam artifact{
  BorderColor black
  BackgroundColor transparent
}
skinparam artifact{
  BorderColor black
  BackgroundColor transparent
}
skinparam node{
  BorderColor black
  BackgroundColor transparent
}
skinparam rectangle {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}

node "Docker Runtime" <<Eligible Party Infrastructure>> as epInfra{
  artifact "EDDIE Framework" as eddie
  artifact "\nServices\n" as service
  interface "Kafka" as eddie1
  interface "Kafka" as eddie2

  eddie -right- eddie1
  service -left-( eddie1 :Consume historical \nand real-time data
  eddie -left- eddie2
}

node "Docker Runtime" <<In-house Device>> as house{
  artifact AIIDA as aiida
}
node " " <<Smart Meter>> as meter{
  interface "P1" as p1
  rectangle "\n" as dummy
  dummy -[hidden]left- p1
}

node " " <<Energy Provider Infrastructure>> as energyProvider {
  interface "HTTP" as energy1
}

' actor "Consumer" as consumer
' actor "Eligible\nParty" as ep

aiida -right-( p1 :"              Get real-time data         "

eddie -down-( energy1 :Get historical data
aiida -down-( eddie2 :Send real-time data

' consumer -down- aiida
' ep -down- eddie

@enduml