@startuml external-interfaces
'component diagram

' skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}

skinparam component {
  BorderColor black
  BackgroundColor transparent
  ArrowColor black
  ArrowFontColor black
}


component [EDDIE\nFramework] as eddie 
' #ffbd38
component [Energy\nProvider] as energy
' #52cbff
component [AIIDA\n] as aiida
' #7aff83
component [Services\n] as services
' #ff52ab

'''''''''''with interfaces'''''''''''
interface " " as eddie1
interface " " as eddie2
interface " " as energy1

eddie -right- eddie1
services -left-( eddie1 :Consumes data

eddie -left- eddie2
aiida -right-( eddie2 :Sends real-time data

energy -right- energy1
eddie -down-( energy1 :Gets historical data
''''''''''with interfaces'''''''''''

' '''''''''''without interfaces'''''''''''
' eddie -right-> services :all energy data

' aiida -right-> eddie :real-time data

' energy -up-> eddie :historical data
' '''''''''''without interfaces'''''''''''

@enduml