@startuml regional-data-sharing-infr
'component diagram
caption Component Diagram: Regional Data-sharing Infrastructure

skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}
skinparam component{
  BorderColor black
  BackgroundColor transparent
}
skinparam collections{
  BorderColor black
  BackgroundColor white
}


node "Eligible Party Infrastructure"  as epInfra{
  component "EDDIE Framework" as eddie {
    component "Interoperable Communication" as comm {
      collections "\t\tRegional Connector\t\t\n" as regCon
    }
  }
}
node "Regional Data-sharing\nInfrastructure" as energyProvider{
  interface "Consent\nAdmin\nPortal" as adminPortal
  interface "Meter\nData\nPortal" as dataPortal
  
}
regCon ---down-( dataPortal : Access\ndata
regCon ---down-( adminPortal : Establish\nConsent

@enduml