@startuml get-historical-data-austria
'sequence diagram
caption Sequence Diagram: The consumer gives consent to an eligible party for access to historical data.

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber

actor "Consumer" as user
participant "EP\nWebsite" as website
box "EDDIE Framework" #transparent
  participant "Consent\nFacade" as facade
  participant "Interoperable\nCommunication" as comm
  participant "Consent\nFacade" as facade
end box
box "EDA" #transparent
participant "Consent\nAdmin Portal" as adminPortal
end box
box "DSO" #transparent
participant "Meter Data\nPortal" as dataPortal
end box

user -> website : login()
user -> website : connectMyData()
activate website
  website -> facade : getConsentPortals()
    activate facade
    facade -->> website : countries,\nadminPortals
  deactivate facade
  website -->> user : show(countries,\nadminPortals)
deactivate website

user -> website : select(admin\nPortal)
activate website
  website -> facade : forward(adminPortal)
  activate facade
    facade -> comm : get\nConsent(\nconsumer)
    comm -> adminPortal : requestConsent(consumer, EP)
    adminPortal -> dataPortal : forward(\nconsentRequest)
    facade -->> website : OK
  deactivate facade
  website -->> user : redirectTo(\ndataPortal)
deactivate website

user -> dataPortal : login()
user -> dataPortal : acceptConsentRequest()
dataPortal -> adminPortal : send(\nhistoricalData)
adminPortal -> comm : send(historicalData)

@enduml