@startuml regional-connector-austria-request-consent
'sequence diagram
caption Sequence Diagram: The Regional Connector of Austria Requesting Consent

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber

!pragma teoz true

box "EDDIE Framework" #transparent
participant "Consent\nFacade" as consentFacade
  box "Interoperable Communication\n" #transparent
    box "Regional Connector - Austria" #transparent
      participant "Translation\nService" as translationService
      participant "Ponton\nAdapter" as pontonAdapter
      participant "Ponton XP\nMessanger" as pontonXP
    end box 
  end box
end box
participant "Consent\nAdmin Portal" as adminPortal

consentFacade -> translationService : getConsent(\nconsumer)
translationService -> pontonAdapter : send(\nconsentRequest)
pontonAdapter -> pontonXP : forward(\nconsentRequest)
pontonXP -> adminPortal : requestConsent(\nconsumer, EP)


@enduml