@startwbs stakeholders
'work breakdown structure

<style>
wbsdiagram {
  node {
    BackgroundColor transparemt
    HorizontalAlignment center
    fontsize 14
  }
'   :depth(3) {
'     Linecolor white
'   }
}
</style>

* Architecture Stakeholders

++ System \nusers
+++_ Customers
+++_ Eligible parties
+++_ Open-source \ncommunity

++ System \ndevelopers
+++_ EDDIE project \ndevelopers
+++_ Architecture \ndecision-makers
+++_ Open-source \ncommunity


++ System \noperators
+++_ Energy data-sharing \ninfrastructure operators
+++_ IT system operators




@endwbs