@startuml deployment-diagram-level-2
' Deployment Diagram: Level 2 view

skinparam linetype ortho
skinparam rectangle {
  BorderColor black
  BackgroundColor transparent
  FontColor black
}

node "\t\t\tAIIDA\t\t\t\n\n" as aiidaSystem
node "\t\tEDDIE Framework\t\t\n\n" as eddieSystem
node "\t\tMarketplace\t\t\t\n\n" as marketplaceSystem

' Communication lines with protocols
aiidaSystem -down-> eddieSystem : "MQTT"
marketplaceSystem -left-> aiidaSystem : "HTTP"

@enduml
