@startuml aiida
'component diagram
caption Component Diagram: AIIDA

skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}
skinparam component{
  BorderColor black
  BackgroundColor transparent
}
skinparam actor{
  BorderColor black
  BackgroundColor transparent
}
skinparam database{
  BorderColor black
  BackgroundColor transparent
}
skinparam rectangle{
  BorderColor black
  BackgroundColor transparent
}

node "Eligible Party Infrastructure"  as epInfra{
  component "EDDIE Framework" {

    component "Streaming\nInfrastructure" as streaming
  }
}
node "In-house\nInfrastructure" {
  component "\tAIIDA" as aiida {
    component "AIIDA\nFrontend" as frontend
    component "  AIIDA\n  Backend" as backend
    interface " " as aiidaAPI

    frontend -right-( aiidaAPI
    aiidaAPI -right- backend
  }
  node "Smart Meter" as meter {
    interface "Smart Meter\nInterface" as p1
  }
  backend -down-( p1
}
interface " " as streamAPI
actor "customer" as customer
component "AIIDA\nApp" as app

streaming -down- streamAPI
backend -up-( streamAPI
customer -down- frontend

customer -right- app
app -down-( aiidaAPI

@enduml