@startuml eda-enedis
folder "MVP-1 Scope" {
    [EDDIE] as Eddie #lightblue
    () "CIM/Kafka" as EddieData
    () "Consent" as EddieConsent
    EddieData -- Eddie
    EddieConsent -- Eddie

    [Demo Application] as Demo
    Demo ..> EddieData
    Demo ..> EddieConsent
}

component [EDA] as Eda
() "Ponton X/P" as EdaData
() "EDA permission as of CCM1.1" as EdaConsent
EdaData -- Eda
EdaConsent -- Eda
Eddie ..> EdaData
Eddie ..> EdaConsent

component [ENEDIS] as Enedis
() "Metering v5\n(REST-like data)" as EnedisData
() "Jeton v3\n(OAuth 2.0 permission)" as EnedisConsent
EnedisData -- Enedis
EnedisConsent -- Enedis
Eddie ..> EnedisData
Eddie ..> EnedisConsent
@enduml