@startuml component-diagram-level-2
'component diagram
caption Component Diagram: Level 2 view

skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}
skinparam component{
  BorderColor black
  BackgroundColor transparent
}
skinparam actor{
  BorderColor black
  BackgroundColor transparent
}
skinparam database{
  BorderColor black
  BackgroundColor transparent
}
skinparam collections{
  BorderColor black
  BackgroundColor white
}
skinparam rectangle{
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}


node "Eligible Party Infrastructure"  as epInfra{
  component "EDDIE Framework" {    
    component "Permission \nFacade" as consentFacade
    component "Streaming\nInfrastructure" as broker
    database "Database\n" as database
    component "Admin \nConsole" as adminConsole
    component "\t\t\t\t\tInteroperable Communication\t\t\t\t\t" as comm
  }
 
    component "EP Website" as ui
    collections "Service" as services
  

  ui -down(0- consentFacade
  ui -[hidden]right- services
  consentFacade -right- broker
  consentFacade -down- comm
  broker -right- database
  broker -down- comm
  database -right-adminConsole
  broker -up0)- services
  adminConsole -down- comm

}
node "In-house\nInfrastructure" {
  component "\tAIIDA\t" as aiida
  node "Smart Meter" as meter {
      interface "Smart Meter\nInterface" as p1
  }
  aiida -down-( p1 
}

node "Regional Data-sharing\nInfrastructure" as energyProvider {
  interface "Meter\nData\nPortal" as dataPortal
  interface "Consent\nAdmin\nPortal" as adminPortal
}

actor "Customer" as consumer
actor "Eligible\nParty" as ep

component "Marketplace" as marketplace

consumer -right- marketplace
marketplace -down- ep


ep -left- adminConsole

consumer -down- aiida
consumer - ui

comm -down-( dataPortal
comm -down-( adminPortal

aiida -up(0- comm

@enduml