@startuml component-diagram-level-2
'component diagram
caption Component Diagram: Level 2 view

skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}
skinparam component{
  BorderColor black
  BackgroundColor transparent
}
skinparam actor{
  BorderColor black
  BackgroundColor transparent
}
skinparam database{
  BorderColor black
  BackgroundColor transparent
}
skinparam rectangle{
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}


node "Eligible Party Infrastructure"  as epInfra{
  component "EDDIE Framework" {    
    component "Consent \nFacade" as consentFacade
    component "Streaming\nInfrastructure" as broker
    database "Database\n" as database
    component "Admin \nConsole" as adminConsole
    component "\t\t\t\t    Interoperable Communication\t\t\t\t\t" as comm
  }
 
    component "User Interface \n(Website or App)" as ui
    component "Services" as services
  

  ui -down(0- consentFacade
  ui -[hidden]right- services
  consentFacade -right- broker
  consentFacade -down- comm
  broker -right- database
  broker -down- comm
  database -right-adminConsole
  broker -up0)- services
  adminConsole -down- comm

}
node "In-house\nInfrastructure" {
  component "\tAIIDA\t" as aiida
  node "Smart Meter" as meter {
      interface "P1" as p1
  }
  aiida -down-( p1 
}

node "Regional Data-sharing\nInfrastructure" as energyProvider {
  interface "Meter\nData\nPortal" as dataPortal
  interface "Consent\nAdmin\nPortal" as adminPortal
}

actor "Consumer" as consumer
actor "Eligible\nParty" as admin
  admin -left- adminConsole

consumer -down- aiida
consumer - ui

comm -down-( dataPortal
comm -down-( adminPortal

aiida -up(0- comm

@enduml