@startuml component-diagram-level-3-inter-comm
'component diagram
caption Component Diagram: Level 3 view with focus on the Interoperable Communication

skinparam linetype ortho
skinparam interface {
  backgroundColor transparent
  borderColor black
}
skinparam component{
  BorderColor black
  BackgroundColor transparent
}
skinparam collections{
  BorderColor black
  BackgroundColor white
}
skinparam database{
  BorderColor black
  BackgroundColor transparent
}
skinparam rectangle{
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}

node "Eligible Party Infrastructure"  as epInfra{
  component "EDDIE Framework" as eddie {
  component "Consent Facade" as consentFacade
  component "Interoperable Communication" as comm {
    component "Regional Connector\nAustria" as regConAu
    component "Regional Connector\nFrance" as regConFr
    collections "Regional Connector\nOther" as regConOt
    component "Message\nProducer" as messageProducer
    
    regConFr -down-> messageProducer
    regConAu -down-> messageProducer
    regConOt -right-> messageProducer

    regConAu -[hidden]right- regConFr
  }
    component "Streaming\nInfrastructure" as database
  
  consentFacade --down- comm
  comm -right- database
  }  
}
node "Regional Data-sharing\nInfrastructure" as energyProvider {
  interface "Meter Data Portal" as dataPortal
  interface "Consent Admin Portal" as adminPortal

  adminPortal -[hidden]down- dataPortal 
}

comm -down-( dataPortal
comm --down-( adminPortal





@enduml