@startuml service-termination-consumer
'sequence diagram
caption Sequence Diagram: The consumer terminates a running service.

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber

actor "Consumer" as user
participant "EP\nWebsite" as website
participant "Interoperable\nCommunication" as comm
participant "Consent\nAdmin Portal" as adminPortal
participant "Meter Data\n Portal" as meterPortal

user -> website : terminate(\nservice)
activate website
  website -> comm : terminate(\nservice)
    activate comm
      comm -> adminPortal : terminate(\nservice)
      activate adminPortal
        adminPortal -> meterPortal : terminate(\ndataSharing)
        adminPortal -->> comm : consentStatus
      deactivate adminPortal
      comm -->> website : consentStatus
    deactivate comm
  website -->> user : consentStatus
deactivate website

@enduml