on:
  push:
    branches:
      - main
name: Build and Deploy
jobs:
  web-deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up NodeJs 
      uses: actions/setup-node@v3
      with:
        node-version: 19

    - uses: actions/setup-java@v3 
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Run PlantUML Pico Server
      run: |
        curl -L https://github.com/plantuml/plantuml/releases/download/v1.2023.5/plantuml.jar --output plantuml.jar
        java -jar ./plantuml.jar -picoweb:19283 &
        sleep 5
    - name: Build
      run: |
        npm install --ci 
        npm run build
    - name: Deploy
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ secrets.SSH_HOST }}
        remote-user: ${{ secrets.SSH_USERNAME }}
        private-ssh-key: ${{ secrets.SSH_KEY }}
        source-path: ./eleventy/_site/
        destination-path: /web/architecture/
