@startuml aiida_new_connection_qr
'sequence diagram
caption Establish a new connection via QR-Code Scan

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Customer" as user
box "EP Infrastructure" #transparent
  participant "EP Website" as website
  participant "EMQX IAM \nDatabase" as database
end box
box "\tAIIDA Network\t\t"  #transparent
  participant "Smartphone" as smartphone  
    box "AIIDA" #transparent
    participant "AIIDA Regional \nConnector" as connector
       box "AIIDA Embedded App" #transparent
      participant "AIIDA Backend" as backend
    end box
  end box


user -> website : AIIDA connect
activate website

  website -->> user : show (QR-Code/ Token)
deactivate website


  user -> smartphone : scan QR Code, add new permission
  activate smartphone
    smartphone -> backend : add new permission
    deactivate smartphone
    activate backend
    backend -->> connector : establish connection
    activate connector
    deactivate backend
    connector -> database : create user
    deactivate connector
    activate database
    deactivate database
  deactivate smartphone


@enduml