@startuml aiida_request_data
'sequence diagram

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

' actor customer
box "EP Infrastructure" #transparent
' participant "EP Website" as website
participant "Service" as service
end box
box "\tAIIDA System\t\t"  #transparent
participant "AIIDA Region \nConnector" as connector
participant "Timescale DB" as timescale
participant "AIIDA \nApplication"  as app
participant "Data\n Source" as data_source
end box
participant "Measuring\n Device" as device

device -> data_source : sends energy\ndata
data_source -> app : sends energy\ndata
app -> timescale : stores energy\ndata
app -> connector : publishes energy data via MQTT
connector -> service : subscribes energy \ndata via MQTT

' website -> customer : show energy data
' connector -> website : share energy data

@enduml