@startuml aiida_new_connection_token
'sequence diagram

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Customer" as user
box "EP Infrastructure" #transparent
participant "EP Website" as website
participant "EMQX IAM \nDatabase" as database
end box
box "\tAIIDA System\t\t"  #transparent
participant "AIIDA Region \nConnector" as connector
box "\t\tAIIDA Application\t\t"  #transparent
participant "AIIDA UI" as frontend
participant "AIIDA Backend" as backend
end box
end box

user -> website : connect AIIDA
activate website
website -> connector : request QR code, token
activate connector
connector -->> website : QR code, token
deactivate connector
website -->> user : show QR code,\ntoken
deactivate website

user -> frontend : add token (manually or via QR code), add new permission
frontend -> backend : token information\npermission
backend -> connector : establish connection via MQTT
connector -> database : create user

@enduml