@startuml aiida_request_data
'sequence diagram
caption The customer requests data through EDDIE  Framework

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true
actor customer

box "Device" as device
end box

box "EP Infrastructure" #transparent

    participant "EP Website" as website
       participant "EP Service" as service
      participant "EMQX IAM \nDatabase" as database
    participant "EMQX MQTT \nBroker" as mqttbroker
end box
    box "\tAIIDA\t\t"  #transparent
    participant "AIIDA Regional \nConnector" as connector
     participant "Timescale DB" as timescale
      participant "AIIDA \nEmbedded App"  as app
      participant "MQTT Broker" as broker
  end box



device -> broker : send energy data
broker -> timescale : store energy data
broker -> mqttbroker : share energy data 
mqttbroker -> website : share energy data  
website -> customer : show energy data
mqttbroker -> service : share energy data
@enduml