@startuml aiida_send_data
'sequence diagram
caption The in-house devices send data to EDDIE Framework

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true
actor customer

box "Device" as device
end box

box "EP Infrastructure" #transparent

    participant "EP Website" as website
      participant "EMQX IAM \nDatabase" as database
    participant "EMQX MQTT \nBroker" as mqttbroker
end box
    box "\tAIIDA\t\t"  #transparent
    participant "AIIDA Regional \nConnector" as connector
     participant "Timescale DB" as timescale
      participant "AIIDA \nEmbedded App"  as app
      participant "MQTT Broker" as broker
  end box




device -> broker : send energy\ndata
activate broker
broker -> app : send energy data
deactivate broker
activate app
app -> timescale : store energy\ndata
activate timescale
deactivate app
deactivate timescale
customer -> website : login
activate website
website -> database : access user 
activate database
database -->> website : confirm access 
deactivate database


customer -> website : request energy data
website -> connector : forward request

activate connector
connector -> app: ask for permission
deactivate connector
activate app 
app -->> timescale : forward\nrequest
activate timescale
timescale -> app : allow access
deactivate timescale
app -->> mqttbroker  :sends energy data
deactivate app

deactivate connector
activate mqttbroker
deactivate timescale
mqttbroker -->> website : forward energy data
deactivate mqttbroker
deactivate database
website -->> customer : show energy data
deactivate website



@enduml