@startuml aiida_new_connection_token
'sequence diagram
caption Establish a new connection via Token

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

actor "Customer" as user
box "EP Infrastructure" #transparent
  participant "EP Website" as website
  participant "EMQX IAM \nDatabase" as database
end box
    box "\tAIIDA\t\t"  #transparent
    participant "AIIDA Regional \nConnector" as connector
      box "\t\tAIIDA Embedded App\t\t"  #transparent
      participant "AIIDA Frontend" as frontend
      participant "AIIDA Backend" as backend
    end box
  end box


user -> website : AIIDA connect
activate website

  website -->> user : show (QR-Code/ Token)
deactivate website


  user -> frontend : insert Token, add new permission
 
      frontend -> backend : access

    backend  -->> connector : establish connection

    connector -->> database : create user




@enduml