@startuml aiida_request_data
'sequence diagram

skinparam style strictuml
skinparam sequence {
  ParticipantBackgroundColor transparent
  ActorBackgroundColor transparent
}

autonumber
!pragma teoz true

' actor customer
box "EP Infrastructure" #transparent
' participant "EP Website" as website
participant "Service" as service
end box
box "\tAIIDA System\t\t"  #transparent
participant "AIIDA Regional \nConnector" as connector
participant "Timescale DB" as timescale
participant "AIIDA \nEmbedded App"  as app
participant "Adapter\n Device" as adapter
end box
participant "Metering\n Device" as device

device -> adapter : sends energy\ndata
adapter -> app : sends energy\ndata
app -> timescale : stores energy\ndata
app -> connector : streams energy data via MQTT
connector -> service : streams energy \ndata via Kafka

' website -> customer : show energy data
' connector -> website : share energy data

@enduml